blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/cjRem44x/CRZLib/discussions
    about: Ask questions or discuss ideas
  - name: Security Vulnerability
    url: https://github.com/cjRem44x/CRZLib/security/policy
    about: Report security vulnerabilities privately
